---
jobs:
- name: apply-rules
  public: true
  plan:
  - get: gitrepo
    trigger: false
  - task: apply-rules
    file: gitrepo/aptomi-task.yml
    input_mapping:
      repo: gitrepo
    params:
      ACTION: apply
      FILEPATH: repo/((rules-policy))

resources:
- name: gitrepo
  type: git
  source:
    uri: ((repo))

